version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: 'rabbitmq_container'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  shipping:
    image: ghcr.io/indra-yana/shipping-service:latest
    restart: always
    ports:
      - 3001:3001
    #volumes:
    #  - .:/src
    depends_on:
      - rabbitmq
    environment:
      PORT: 3001
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
